"""
One-command reproduction of the whole paper.

Runs every OFFLINE analysis script in dependency order (each reads the committed,
public `data/*.csv` and regenerates its derived CSVs + figures), then recomputes
every headline number quoted in the manuscript from the production code and checks
it against the prose, writing `notes/reproduction_manifest.md`.

    python3 src/reproduce.py

Exit status is 0 only if (a) every script ran clean and (b) every canonical number
reconciles in BOTH the code and the prose. This is what backs the paper's
"released, reproducible pipeline" claim — a referee runs one command.

UPSTREAM HARVEST (network, not run here). `src/nport_fetch.py` and
`src/nport_timeseries.py` rebuild `data/fund_marks.csv` and
`data/fund_marks_timeseries.csv` from live SEC EDGAR (public domain). They need a
declared User-Agent and are resumable; run them only to refresh the SEC harvest.
The committed CSVs let everything below reproduce offline.

PDF: `src/build_pdf.py` renders `paper/unicorn_valuation_disagreement.pdf` and needs
a working `xelatex`; it is intentionally not invoked here (no LaTeX dependency for
reproducing the numbers).
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

# Offline scripts in dependency order. Each is self-contained (reads data/, writes
# figures/ and derived data/). nport_fetch / nport_timeseries (network) excluded.
SCRIPTS = [
    ("src/validation.py", "§7 IPO-exit validation"),
    ("src/fund_marks.py", "§4.3 cross-fund dispersion"),
    ("src/robustness.py", "Appendix D robustness suite"),
    ("src/level1_placebo.py", "§2.3 Level-1 placebo (public-mark falsification)"),
    ("src/mark_staleness.py", "Appendix D staleness test on the cross-family spread"),
    ("src/fund_complex.py", "registrant -> fund complex map and its coverage"),
    ("src/population.py", "population panel: concentration, persistence, house policy"),
    ("src/population_figure.py", "population figure: the spread distribution and its dollars"),
    ("src/fund_marks_bulk.py", "the ten §4.3 cells with the harvest cap lifted"),
    ("src/company_class.py", "what kind of company each cluster is, and on what basis"),
    ("src/p4_pretest.py", "P4 run on the pre-2023 exits, exploratory"),
    ("src/reconcile_versions.py", "published cells recomputed from the bulk data"),
    # The three sensors of §9 that need no network: the N-CSR harvest is excluded for the
    # same reason nport_fetch is. `round_event_study` is last because it consumes the other
    # two, and it writes the statistics file the manuscript guard pins §8's prose against.
    ("src/split_events.py", "§9.2 share splits read off the panel"),
    ("src/round_dates.py", "§9.3 round dates from the first appearance of a series letter"),
    ("src/round_event_study.py", "§8 the event study, and its committed statistics"),
    ("src/nav_wedge.py", "§11 the NAV wedge, and whether it is forecastable"),
    # Last, because it reads the panels and the event-study statistics the stages above
    # write. A figure built from a stale statistics file is the drift this whole file
    # exists to catch, one artifact further out than the prose.
    ("src/paper_figures.py", "the three figures §2.1, §3.3 and §8 need"),
]


def run_scripts(only: set[str] | None = None) -> list[tuple[str, bool, float]]:
    """Run the offline stages in dependency order.

    `only` restricts the run to the named stages (module stems). The full pipeline takes
    about five minutes, which is longer than some sandboxes allow a single command, so a
    stage subset can be run in parts and the stages that were skipped are printed as SKIP
    rather than silently omitted — a partial run must never be able to look like a clean one.
    """
    results = []
    print("=" * 78)
    print("REPRODUCE — offline analysis pipeline")
    print("=" * 78)
    for rel, desc in SCRIPTS:
        if only is not None and Path(rel).stem not in only:
            print(f"  [SKIP] {rel:<34}        {desc}")
            continue
        t0 = time.time()
        proc = subprocess.run([sys.executable, str(ROOT / rel)], check=False,
                              capture_output=True, text=True)
        dt = time.time() - t0
        ok = proc.returncode == 0
        print(f"  [{'PASS' if ok else 'FAIL'}] {rel:<34} {dt:5.1f}s  {desc}")
        if not ok:
            print("    ---- stderr ----")
            print("    " + "\n    ".join(proc.stderr.strip().splitlines()[-12:]))
        results.append((rel, ok, dt))
    return results


def write_manifest(nums) -> Path:
    import paper_numbers as pn
    lines = [
        "# Reproduction manifest — canonical paper numbers",
        "",
        "Auto-generated by `python3 src/reproduce.py`. Every figure quoted in the paper,",
        "recomputed live from the production code (`src/paper_numbers.py::canonical_numbers`)",
        "and checked against the manuscript prose. Do not edit by hand.",
        "",
        "- **code**: `|computed - paper| <= tol` (the loaders still produce the quoted value).",
        "- **prose**: the quoted token is present in every file that should state it",
        "  (drift guard — `paper/draft.md`, `README.md`).",
        "",
        "| § | claim | computed | paper | tol | code | prose | what |",
        "| --- | --- | ---: | ---: | ---: | :---: | :---: | --- |",
    ]
    for n in nums:
        if n.claim or n.context:
            miss = pn.prose_missing(n)
            prose = "OK" if not miss else "MISS: " + "; ".join(miss)
            claim = "`" + n.claim + "`" if n.claim else "_(context)_"
        else:
            prose, claim = "—", "_(numeric)_"
        code = "OK" if n.code_ok else "DRIFT"
        lines.append(f"| {n.section} | {claim} | {n.computed:.3f} | {n.value:.3f} | "
                     f"{n.tol:g} | {code} | {prose} | {n.label} |")
    bad_code = sum(not n.code_ok for n in nums)
    bad_prose = sum(bool(pn.prose_missing(n)) for n in nums)
    lines += ["",
              f"**{len(nums)} canonical numbers — {bad_code} code-drift, {bad_prose} prose-drift.**",
              ""]
    out = ROOT / "notes" / "reproduction_manifest.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", default=None,
                    help="comma-separated stage stems to run (default: all). The number "
                         "check and the manifest always run over the whole registry.")
    args = ap.parse_args(argv)
    only = {x.strip() for x in args.only.split(",")} if args.only else None
    if only:
        known = {Path(r).stem for r, _ in SCRIPTS}
        unknown = only - known
        if unknown:
            raise SystemExit(f"unknown stage(s): {sorted(unknown)}")
    results = run_scripts(only)
    script_fail = [r for r, ok, _ in results if not ok]

    print("\n" + "=" * 78)
    print("CANONICAL NUMBERS — recompute from code, check against prose")
    print("=" * 78)
    import paper_numbers as pn
    nums = canonical = pn.canonical_numbers()
    pn._print_table(nums)
    manifest = write_manifest(nums)

    bad_code = [n for n in canonical if not n.code_ok]
    bad_prose = [n for n in canonical if pn.prose_missing(n)]

    print(f"\nwrote {manifest.relative_to(ROOT)}")
    print("=" * 78)
    print(f"scripts: {len(results) - len(script_fail)}/{len(SCRIPTS)} run and passed   "
          f"numbers: {len(canonical)} checked, {len(bad_code)} code-drift, "
          f"{len(bad_prose)} prose-drift")
    ok = not script_fail and not bad_code and not bad_prose
    if only:
        print(f"NOTE: partial stage run ({len(results)} of {len(SCRIPTS)} stages); the "
              "canonical-number check above covers the whole registry regardless.")
    print("RESULT:", "REPRODUCED CLEAN ✓" if ok else "FAILURES ABOVE ✗")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
